/*
Copyright 2020 The arhat.dev Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package network

import (
	"context"
	"io"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestClient_CreateResolvConf(t *testing.T) {
	client := NewClient(
		func(
			ctx context.Context,
			env map[string]string,
			stdin io.Reader,
			stdout, stderr io.Writer,
		) error {
			return nil
		},
	)

	var (
		nameservers = []string{"8.8.8.8", "1.1.1.1"}
		searches    = []string{"foo", "bar"}
		options     = []string{"foo:1", "bar:2"}
	)
	data, err := client.CreateResolvConf(nameservers, searches, options)
	assert.NoError(t, err, "failed to create resolv.conf")
	if !assert.Equal(t, `# resolv.conf generated by ext.arhat.dev/runtimeutil
nameserver 8.8.8.8
nameserver 1.1.1.1
search foo bar
options foo:1 bar:2
`, string(data)) {
		t.Log(string(data))
	}
}
